### PR TITLE
build: add support for different architecture

### PR DESCRIPTION
**Pull request by mashirozx**

### CODE REVIEW

**Comment by mashirozx** [comment]
@TimothyYe ready

**Comment by mashirozx** [comment]
这次可以合了，测试在[这](https://github.com/mashirozx/bing-wallpaper/runs/6893165010?check_suite_focus=true) ，建议合的时候选择 squash merge
@TimothyYe

**Comment by mashirozx** [comment]
Hello? Ready to merge, test [here](https://github.com/mashirozx/bing-wallpaper/runs/6893165010?check_suite_focus=true). It's recommended to squash merge this pr. @TimothyYe

**Comment by TimothyYe** [comment]
谢谢，出去休假了两天，没带电脑

**Comment by mashirozx** [comment]
幸苦了

**Pull request merged**
